# Jekyll 配置文件
title: Kongfy's Blog
description: good good code, day day up!
url: "https://your-domain.com" # 请替换为你的实际域名
baseurl: ""

# 作者信息
author:
  name: Fanyu Kong
  email: njukongfy@gmail.com

# 构建设置
markdown: kramdown
permalink: /posts/:year/:month/:title/
timezone: Asia/Shanghai

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Disqus 评论系统
disqus:
  shortname: your-disqus-shortname  # 请替换为你的 Disqus shortname

# 显示设置
show_excerpts: true

# 语言设置
lang: zh-CN

